build:
	cp -r ../../. /app
	apk add py-pip build-base
	# install semgrep
	mkdir /toolbox/venv
	pip install --target=/toolbox/venv semgrep
	ls /toolbox/venv
	ls /toolbox/venv/bin
	ls /toolbox
	ls /macrocode
